import React,{useEffect,useState} from 'react';
import type {ModuleSummary,ModuleSaveInput,ModuleGroup} from '../../../shared/moduleTypes';
import {fetchAdminModules,createAdminModule,updateAdminModule} from '../../api/modules';
export function ModuleMasterTable({modules,canManage,onEdit,onToggle,busy=false}:{modules:ModuleSummary[];canManage:boolean;onEdit:(m:ModuleSummary)=>void;onToggle:(m:ModuleSummary)=>void;busy?:boolean}){
 return <div className="module-table-scroll"><table><thead><tr><th>Group</th><th>Code</th><th>Name</th><th>Description</th><th>Status</th>{canManage&&<th>Actions</th>}</tr></thead><tbody>{modules.map(m=><tr key={m.id}><td>{m.group}</td><td>{m.code}</td><td>{m.name}</td><td>{m.description||'—'}</td><td>{m.isActive?'Active':'Inactive'}</td>{canManage&&<td><div className="module-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>onEdit(m)}>Edit</button><button type="button" className="secondary" disabled={busy} onClick={()=>onToggle(m)}>{m.isActive?'Deactivate':'Reactivate'}</button></div></td>}</tr>)}</tbody></table>{!modules.length&&<p>No modules found.</p>}</div>;
}
const emptyForm:ModuleSaveInput={group:'SAP',code:'',name:'',description:'',isActive:true};
export function ModuleMasterPanel({canManage}:{canManage:boolean}){
 const [modules,setModules]=useState<ModuleSummary[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 const [group,setGroup]=useState('');const [search,setSearch]=useState('');const [status,setStatus]=useState('all');
 const [editing,setEditing]=useState<number|null>(null);const [open,setOpen]=useState(false);const [form,setForm]=useState(emptyForm);
 async function load(){setLoading(true);try{setModules(await fetchAdminModules());setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const result=editing?await updateAdminModule(editing,form):await createAdminModule(form);setModules(prev=>[...prev.filter(m=>m.id!==result.id),result].sort((a,b)=>a.group.localeCompare(b.group)||a.code.localeCompare(b.code)));setOpen(false);setMessage('Module saved.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function toggle(m:ModuleSummary){setBusy(true);setError('');try{const result=await updateAdminModule(m.id,{...m,description:m.description||'',isActive:!m.isActive});setModules(prev=>prev.map(row=>row.id===result.id?result:row));setMessage(result.isActive?'Module activated.':'Module deactivated.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 const filtered=modules.filter(m=>(!group||m.group===group)&&(status==='all'||m.isActive===(status==='active'))&&(!search||(m.code+' '+m.name).toLowerCase().includes(search.toLowerCase())));
 return <section className="panel module-master-panel"><div className="module-toolbar"><h2>Modules</h2>{canManage&&<button type="button" disabled={busy} onClick={()=>{setEditing(null);setForm(emptyForm);setOpen(true);setError('');setMessage('');}}>Add Module</button>}</div>
 <p>Maintain modules used to classify Issues.</p>
 <div className="module-filters"><label>Group<select value={group} onChange={e=>setGroup(e.target.value)}><option value="">All groups</option><option>SAP</option><option>NON-SAP</option></select></label><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search code or name"/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button type="button" className="secondary" disabled={busy||loading} onClick={()=>void load()}>Refresh</button></div>
 {error&&<p role="alert">{error} <button type="button" className="secondary" disabled={busy} onClick={()=>void load()}>Retry</button></p>}{message&&<p role="status">{message}</p>}
 {open&&canManage&&<form className="module-master-form" onSubmit={save}><h3>{editing?'Edit Module':'Add Module'}</h3><label>Group<select disabled={!!editing||busy} value={form.group} onChange={e=>setForm({...form,group:e.target.value as ModuleGroup})}><option>SAP</option><option>NON-SAP</option></select></label><label>Code<input required disabled={!!editing||busy} value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Name<input required disabled={busy} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Description<textarea disabled={busy} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="module-option"><input type="checkbox" disabled={busy} checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/>Active</label><div className="module-actions"><button disabled={busy} type="submit">{busy?'Saving...':'Save Module'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button></div></form>}
 {loading?<p role="status">Loading modules...</p>:<ModuleMasterTable modules={filtered} canManage={canManage} busy={busy} onEdit={m=>{setEditing(m.id);setForm({...m,description:m.description||''});setOpen(true);setError('');setMessage('');}} onToggle={m=>void toggle(m)}/>}
 </section>;
}
