export const transportProgramIdDescriptions: Record<string, string> = {
  CORR: "Correction and transport entry",
  LIMU: "Repository sub-object",
  R3TR: "Repository object"
};

export const transportObjectTypeDescriptions: Record<string, string> = {
  ADIR: "Object directory entry",
  AUTH: "Authorization object",
  BSVS: "Status schema",
  CDAT: "Customizing data",
  CINS: "BC set content",
  CLAS: "Class",
  CINC: "Class include",
  CLSD: "Class definition",
  CMOD: "Enhancement project",
  CORR: "Correction",
  CPUB: "Class public section",
  CPRI: "Class private section",
  CPRO: "Class protected section",
  CUAD: "GUI status",
  DEVC: "Package",
  DOCU: "Documentation",
  DOMA: "Domain",
  DOMD: "Domain definition",
  DTEL: "Data element",
  DTED: "Data element definition",
  DYNP: "Screen",
  ENHO: "Enhancement implementation",
  ENHS: "Enhancement spot",
  FUNC: "Function module",
  FUGR: "Function group",
  FUGT: "Function group text",
  INDX: "Technical index object",
  INTF: "Interface",
  MESS: "Message",
  METH: "Class method",
  MSAG: "Message class",
  NOTE: "SAP Note",
  PRIN: "Print object",
  PROG: "Program",
  RELE: "Release information",
  REPS: "Source/include ABAP",
  REPT: "Program text",
  SBXL: "Business object extension",
  SBXP: "Business object extension part",
  SCVI: "View cluster",
  SHLP: "Search help",
  SPDV: "Standard variant",
  SSFO: "Smart Form",
  SSST: "Smart Style",
  STVI: "View cluster object",
  SUSC: "Authorization field",
  SUSO: "Authorization object",
  SXCI: "Customer enhancement implementation",
  TABD: "Table contents",
  TABL: "Table",
  TABT: "Table text",
  TABU: "Table contents",
  TDAT: "Table technical settings",
  TEXT: "Text object",
  TOBJ: "Transport object",
  TRAN: "Transaction",
  TTYP: "Table type",
  VARX: "Variant",
  VDAT: "View data",
  XSLT: "XSLT transformation",
  VIEW: "View"
};

export const transportObjectPairLabels: Record<string, string> = {
  "CORR RELE": "Release information",
  "LIMU CINC": "Class include",
  "LIMU CLSD": "Class definition",
  "LIMU CPUB": "Class public section",
  "LIMU CPRI": "Class private section",
  "LIMU CPRO": "Class protected section",
  "LIMU CUAD": "GUI status",
  "LIMU FUNC": "Function module",
  "LIMU FUGT": "Function group text",
  "LIMU METH": "Class method",
  "LIMU REPS": "Source/include ABAP",
  "LIMU REPT": "Program text",
  "LIMU TABD": "Table contents",
  "R3TR CLAS": "Class",
  "R3TR DOMA": "Domain",
  "R3TR DTEL": "Data element",
  "R3TR ENHO": "Enhancement implementation",
  "R3TR ENHS": "Enhancement spot",
  "R3TR FUGR": "Function group",
  "R3TR INTF": "Interface",
  "R3TR MSAG": "Message class",
  "R3TR PROG": "Program",
  "R3TR SHLP": "Search help",
  "R3TR TABL": "Table",
  "R3TR TRAN": "Transaction",
  "R3TR TTYP": "Table type",
  "R3TR VIEW": "View"
};

export function transportObjectLabel(pgmid?: string, objectType?: string) {
  const key = `${pgmid || ""} ${objectType || ""}`.trim().toUpperCase();
  if (transportObjectPairLabels[key]) return transportObjectPairLabels[key];
  const normalizedObjectType = String(objectType || "").trim().toUpperCase();
  if (transportObjectTypeDescriptions[normalizedObjectType]) return transportObjectTypeDescriptions[normalizedObjectType];
  return key || "Object";
}
