import { Router } from "express";
import { config } from "../config";
import { createSession, findUser, revokeToken, setPassword, verifyPassword } from "../auth/authService";
import { requireAuth } from "../auth/middleware";
import { pool } from "../db/pool";
export const authRoutes = Router();
const publicUser = (user: any) => ({ id: user.id, username: user.username, role: user.role, mustChangePassword: user.must_change_password ?? user.mustChangePassword });
const cookie = (token: string, maxAge: number) => `${config.auth.cookieName}=${token}; Path=/; Max-Age=${maxAge}; HttpOnly; SameSite=Lax${config.auth.cookieSecure ? "; Secure" : ""}`;
authRoutes.get("/me", requireAuth, (req, res) => res.json({ user: req.authUser }));
authRoutes.post("/login", async (req, res, next) => { try { const user = await findUser(String(req.body?.username || "")); const password = String(req.body?.password || ""); if (!user || !user.is_active || !(await verifyPassword(password, user.password_hash))) return res.status(401).json({ message: "Username atau password salah" }); const token = await createSession(user.id, req); await pool.query("UPDATE app_users SET last_login_at = now() WHERE id = $1", [user.id]); res.setHeader("Set-Cookie", cookie(token, config.auth.sessionTtlHours * 3600)); res.json({ user: publicUser(user) }); } catch (error) { next(error); } });
authRoutes.post("/logout", requireAuth, async (req, res, next) => { try { await revokeToken(req.authToken); res.setHeader("Set-Cookie", cookie("", 0)); res.json({ ok: true }); } catch (error) { next(error); } });
authRoutes.post("/change-password", requireAuth, async (req, res, next) => { try { const nextPassword = String(req.body?.newPassword || ""); if (nextPassword.length < 8) return res.status(400).json({ message: "Password minimal 8 karakter" }); const user = await findUser(req.authUser!.username); if (!user || !(await verifyPassword(String(req.body?.currentPassword || ""), user.password_hash))) return res.status(400).json({ message: "Password saat ini salah" }); await setPassword(user.id, nextPassword); res.json({ ok: true }); } catch (error) { next(error); } });
