FUNCTION ZRFC_TRANSPORT_REQUEST_RELEASE.
*"----------------------------------------------------------------------
*" Release transport request (children first, then parent).
*" IV_MODE: TEST_RUN = check only, RELEASE = execute.
*" ET_RESULTS: TRKORR|TRFUNCTION|AS4TEXT|STATUS|MESSAGE|SEQ
*" STATUS: PASS, WARNING, ERROR, RELEASED, SKIPPED
*" Warnings do not block a release; only errors do.
*"----------------------------------------------------------------------

  DATA: LV_TRFUNCTION TYPE E070-TRFUNCTION,
        LV_TRSTATUS   TYPE E070-TRSTATUS,
        LV_AS4TEXT    TYPE E07T-AS4TEXT,
        LV_AS4USER    TYPE E070-AS4USER,
        LV_STRKORR    TYPE E070-STRKORR,
        LT_CHILDREN   TYPE STANDARD TABLE OF E070,
        LS_CHILD      TYPE E070,
        LV_LINE       TYPE ABAPTXT255,
        LV_BUF        TYPE STRING,
        LV_SEQ        TYPE I,
        LV_SEQ_C(3)   TYPE C,
        LV_HAS_ERROR  TYPE C,
        LV_SUBRC      TYPE SY-SUBRC,
        LV_CHILD_TEXT TYPE E07T-AS4TEXT,
        LV_OBJ_CNT    TYPE I,
        LV_RC_C(2)    TYPE C.

  CLEAR: EV_SUCCESS, EV_MESSAGE.
  REFRESH ET_RESULTS.

  IF IV_MODE <> 'TEST_RUN' AND IV_MODE <> 'RELEASE'.
    EV_MESSAGE = 'MODE_NOT_ALLOWED'.
    RETURN.
  ENDIF.
  IF IV_TRKORR IS INITIAL.
    EV_MESSAGE = 'TRKORR_REQUIRED'.
    RETURN.
  ENDIF.

  AUTHORITY-CHECK OBJECT 'S_TRANSPRT'
    ID 'ACTVT' FIELD '43'
    ID 'TTYPE' FIELD 'K'.
  IF SY-SUBRC <> 0.
    EV_MESSAGE = 'AUTHORIZATION_FAILED'.
    RETURN.
  ENDIF.

* --- Parent header ---
  SELECT SINGLE TRFUNCTION TRSTATUS AS4USER STRKORR
    INTO (LV_TRFUNCTION, LV_TRSTATUS,
          LV_AS4USER, LV_STRKORR)
    FROM E070
    WHERE TRKORR = IV_TRKORR.
  IF SY-SUBRC <> 0.
    EV_MESSAGE = 'REQUEST_NOT_FOUND'.
    RETURN.
  ENDIF.
  IF LV_AS4USER <> SY-UNAME.
    EV_MESSAGE = 'NOT_OWNER'.
    RETURN.
  ENDIF.
  IF LV_STRKORR IS NOT INITIAL.
    EV_MESSAGE = 'NOT_A_PARENT_REQUEST'.
    RETURN.
  ENDIF.
  IF LV_TRFUNCTION <> 'K' AND LV_TRFUNCTION <> 'W'.
    EV_MESSAGE = 'INVALID_REQUEST_TYPE'.
    RETURN.
  ENDIF.
  IF LV_TRSTATUS <> 'D'.
    IF LV_TRSTATUS = 'R' OR LV_TRSTATUS = 'N'.
      EV_MESSAGE = 'ALREADY_RELEASED'.
    ELSE.
      EV_MESSAGE = 'REQUEST_NOT_MODIFIABLE'.
    ENDIF.
    RETURN.
  ENDIF.

  SELECT SINGLE AS4TEXT INTO LV_AS4TEXT
    FROM E07T
    WHERE TRKORR = IV_TRKORR AND LANGU = 'E'.
  IF SY-SUBRC <> 0.
    SELECT SINGLE AS4TEXT INTO LV_AS4TEXT
      FROM E07T WHERE TRKORR = IV_TRKORR.
  ENDIF.

  SELECT * INTO TABLE LT_CHILDREN
    FROM E070
    WHERE STRKORR = IV_TRKORR
    ORDER BY TRKORR.

  LV_SEQ = 0.
  LV_HAS_ERROR = SPACE.

  LOOP AT LT_CHILDREN INTO LS_CHILD.
    LV_SEQ = LV_SEQ + 1.
    LV_SEQ_C = LV_SEQ.
    CONDENSE LV_SEQ_C.

    CLEAR LV_CHILD_TEXT.
    SELECT SINGLE AS4TEXT INTO LV_CHILD_TEXT
      FROM E07T
      WHERE TRKORR = LS_CHILD-TRKORR
        AND LANGU = 'E'.
    IF SY-SUBRC <> 0.
      SELECT SINGLE AS4TEXT INTO LV_CHILD_TEXT
        FROM E07T
        WHERE TRKORR = LS_CHILD-TRKORR.
    ENDIF.

*   --- Already released: nothing to do ---
    IF LS_CHILD-TRSTATUS = 'R'
      OR LS_CHILD-TRSTATUS = 'N'.
      CLEAR LV_BUF.
      CONCATENATE LS_CHILD-TRKORR
        LS_CHILD-TRFUNCTION LV_CHILD_TEXT
        'SKIPPED' 'Already released' LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.
      CONTINUE.
    ENDIF.

*   --- Not modifiable: hard error ---
    IF LS_CHILD-TRSTATUS <> 'D'.
      CLEAR LV_BUF.
      CONCATENATE LS_CHILD-TRKORR
        LS_CHILD-TRFUNCTION LV_CHILD_TEXT
        'ERROR' 'Task not modifiable' LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.
      LV_HAS_ERROR = 'X'.
      CONTINUE.
    ENDIF.

*   --- TEST_RUN: report readiness only ---
    IF IV_MODE = 'TEST_RUN'.
      SELECT COUNT(*) INTO LV_OBJ_CNT
        FROM E071
        WHERE TRKORR = LS_CHILD-TRKORR.
      CLEAR LV_BUF.
      IF LV_OBJ_CNT = 0.
        CONCATENATE LS_CHILD-TRKORR
          LS_CHILD-TRFUNCTION LV_CHILD_TEXT
          'WARNING' 'Task has no objects' LV_SEQ_C
          INTO LV_BUF SEPARATED BY '|'.
      ELSE.
        CONCATENATE LS_CHILD-TRKORR
          LS_CHILD-TRFUNCTION LV_CHILD_TEXT
          'PASS' 'Ready for release' LV_SEQ_C
          INTO LV_BUF SEPARATED BY '|'.
      ENDIF.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.
      CONTINUE.
    ENDIF.

*   --- RELEASE: skip empty tasks ---
    SELECT COUNT(*) INTO LV_OBJ_CNT
      FROM E071
      WHERE TRKORR = LS_CHILD-TRKORR.
    IF LV_OBJ_CNT = 0.
      CLEAR LV_BUF.
      CONCATENATE LS_CHILD-TRKORR
        LS_CHILD-TRFUNCTION LV_CHILD_TEXT
        'SKIPPED' 'Empty task skipped' LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.
      CONTINUE.
    ENDIF.

*   --- RELEASE: release this task ---
    CALL FUNCTION 'TR_RELEASE_REQUEST'
      EXPORTING
        IV_TRKORR             = LS_CHILD-TRKORR
        IV_DIALOG             = ' '
        IV_AS_BACKGROUND_JOB  = 'X'
        IV_SUCCESS_MESSAGE    = ' '
        IV_DISPLAY_EXPORT_LOG = ' '
      EXCEPTIONS
        ACTION_ABORTED_BY_USER     = 1
        CTS_INITIALIZATION_FAILURE = 2
        DB_ACCESS_ERROR            = 3
        DOCU_MISSING               = 4
        ENQUEUE_FAILED             = 5
        ERROR_IN_EXPORT_METHODS    = 6
        EXPORT_FAILED              = 7
        INVALID_REQUEST            = 8
        NO_AUTHORIZATION           = 9
        OBJECT_CHECK_ERROR         = 10
        REPEAT_TOO_EARLY           = 11
        REQUEST_ALREADY_RELEASED   = 12
        OTHERS                     = 13.
    LV_SUBRC = SY-SUBRC.

    CLEAR LV_BUF.
    IF LV_SUBRC = 0.
      CONCATENATE LS_CHILD-TRKORR
        LS_CHILD-TRFUNCTION LV_CHILD_TEXT
        'RELEASED' 'Released' LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
    ELSEIF LV_SUBRC = 12.
      CONCATENATE LS_CHILD-TRKORR
        LS_CHILD-TRFUNCTION LV_CHILD_TEXT
        'SKIPPED' 'Already released' LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
    ELSE.
      LV_RC_C = LV_SUBRC.
      CONDENSE LV_RC_C.
      CONCATENATE LS_CHILD-TRKORR
        LS_CHILD-TRFUNCTION LV_CHILD_TEXT
        'ERROR' LV_RC_C LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
      LV_HAS_ERROR = 'X'.
    ENDIF.
    LV_LINE-LINE = LV_BUF.
    APPEND LV_LINE TO ET_RESULTS.
  ENDLOOP.

* --- Parent entry ---
  LV_SEQ = LV_SEQ + 1.
  LV_SEQ_C = LV_SEQ.
  CONDENSE LV_SEQ_C.

  IF IV_MODE = 'TEST_RUN'.
    CLEAR LV_BUF.
    IF LV_HAS_ERROR = 'X'.
      CONCATENATE IV_TRKORR LV_TRFUNCTION LV_AS4TEXT
        'ERROR' 'Blocked by task errors' LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.
      EV_MESSAGE = 'TEST_RUN_HAS_ERRORS'.
    ELSE.
      CONCATENATE IV_TRKORR LV_TRFUNCTION LV_AS4TEXT
        'PASS' 'Ready for release' LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.
      EV_SUCCESS = 'X'.
      EV_MESSAGE = 'TEST_RUN_OK'.
    ENDIF.
    RETURN.
  ENDIF.

* --- Do not release parent if a task failed ---
  IF LV_HAS_ERROR = 'X'.
    CLEAR LV_BUF.
    CONCATENATE IV_TRKORR LV_TRFUNCTION LV_AS4TEXT
      'ERROR' 'Blocked by task errors' LV_SEQ_C
      INTO LV_BUF SEPARATED BY '|'.
    LV_LINE-LINE = LV_BUF.
    APPEND LV_LINE TO ET_RESULTS.
    EV_MESSAGE = 'PARTIAL_RELEASE_TASK_FAILED'.
    RETURN.
  ENDIF.

* --- Release parent ---
  CALL FUNCTION 'TR_RELEASE_REQUEST'
    EXPORTING
      IV_TRKORR             = IV_TRKORR
      IV_DIALOG             = ' '
      IV_AS_BACKGROUND_JOB  = 'X'
      IV_SUCCESS_MESSAGE    = ' '
      IV_DISPLAY_EXPORT_LOG = ' '
    EXCEPTIONS
      ACTION_ABORTED_BY_USER     = 1
      CTS_INITIALIZATION_FAILURE = 2
      DB_ACCESS_ERROR            = 3
      DOCU_MISSING               = 4
      ENQUEUE_FAILED             = 5
      ERROR_IN_EXPORT_METHODS    = 6
      EXPORT_FAILED              = 7
      INVALID_REQUEST            = 8
      NO_AUTHORIZATION           = 9
      OBJECT_CHECK_ERROR         = 10
      REPEAT_TOO_EARLY           = 11
      REQUEST_ALREADY_RELEASED   = 12
      OTHERS                     = 13.
  LV_SUBRC = SY-SUBRC.

  CLEAR LV_BUF.
  IF LV_SUBRC = 0.
    CONCATENATE IV_TRKORR LV_TRFUNCTION LV_AS4TEXT
      'RELEASED' 'Released' LV_SEQ_C
      INTO LV_BUF SEPARATED BY '|'.
    LV_LINE-LINE = LV_BUF.
    APPEND LV_LINE TO ET_RESULTS.
    EV_SUCCESS = 'X'.
    EV_MESSAGE = 'RELEASE_COMPLETE'.
  ELSEIF LV_SUBRC = 12.
    CONCATENATE IV_TRKORR LV_TRFUNCTION LV_AS4TEXT
      'SKIPPED' 'Already released' LV_SEQ_C
      INTO LV_BUF SEPARATED BY '|'.
    LV_LINE-LINE = LV_BUF.
    APPEND LV_LINE TO ET_RESULTS.
    EV_SUCCESS = 'X'.
    EV_MESSAGE = 'RELEASE_COMPLETE'.
  ELSE.
    LV_RC_C = LV_SUBRC.
    CONDENSE LV_RC_C.
    CONCATENATE IV_TRKORR LV_TRFUNCTION LV_AS4TEXT
      'ERROR' LV_RC_C LV_SEQ_C
      INTO LV_BUF SEPARATED BY '|'.
    LV_LINE-LINE = LV_BUF.
    APPEND LV_LINE TO ET_RESULTS.
    EV_MESSAGE = 'PARENT_RELEASE_FAILED'.
  ENDIF.

ENDFUNCTION.
