FUNCTION ZRFC_TRANSPORT_REQUEST_RELEASE.
*"----------------------------------------------------------------------
*" Release transport request (children first, then parent).
*" IV_MODE: TEST_RUN = check only, RELEASE = execute.
*" ET_RESULTS task: TRKORR|TRFUNCTION|AS4TEXT|STATUS|MESSAGE|SEQ
*" ET_RESULTS object:
*" OBJECT|TRKORR|PGMID|OBJECT|OBJ_NAME|STATUS|MESSAGE|SEQ
*" STATUS: PASS, WARNING, ERROR, RELEASED, SKIPPED
*" Warnings do not block a release; only errors do.
*"----------------------------------------------------------------------

  DATA: LV_TRFUNCTION TYPE E070-TRFUNCTION,
        LV_TRSTATUS   TYPE E070-TRSTATUS,
        LV_AS4TEXT    TYPE E07T-AS4TEXT,
        LV_AS4USER    TYPE E070-AS4USER,
        LV_STRKORR    TYPE E070-STRKORR,
        LT_CHILDREN   TYPE STANDARD TABLE OF E070,
        LS_CHILD      TYPE E070,
        LV_LINE       TYPE ABAPTXT255,
        LV_BUF        TYPE STRING,
        LV_SEQ        TYPE I,
        LV_SEQ_C(3)   TYPE C,
        LV_HAS_ERROR  TYPE C,
        LV_SUBRC      TYPE SY-SUBRC,
        LV_CHILD_TEXT TYPE E07T-AS4TEXT,
        LV_OBJ_CNT    TYPE I,
        LV_RC_C(2)    TYPE C,
        LT_OBJECTS    TYPE STANDARD TABLE OF E071,
        LS_OBJECT     TYPE E071,
        LS_REQUEST    TYPE TRWBO_REQUEST,
        LT_MESSAGES   TYPE CTSGERRMSGS,
        LS_MESSAGE    TYPE CTSGERRMSG,
        LT_INACTIVE_LOG TYPE STANDARD TABLE OF SPROT_U,
        LS_INACTIVE_LOG TYPE SPROT_U,
        LS_RELEASE_E070 TYPE TRWBO_S_E070,
        LV_CHECK_RC   TYPE I,
        LV_TASK_STATUS TYPE CHAR10,
        LV_TASK_MESSAGE TYPE CHAR255,
        LV_OBJ_STATUS TYPE CHAR10,
        LV_OBJ_MESSAGE TYPE CHAR255,
        LV_MSG_TEXT   TYPE CHAR255,
        LV_INACTIVE_TEXT TYPE CHAR255,
        LV_OBJ_SEQ    TYPE I,
        LV_OBJ_SEQ_C(3) TYPE C.

  CLEAR: EV_SUCCESS, EV_MESSAGE.
  REFRESH ET_RESULTS.

  IF IV_MODE <> 'TEST_RUN' AND IV_MODE <> 'RELEASE'.
    EV_MESSAGE = 'MODE_NOT_ALLOWED'.
    RETURN.
  ENDIF.
  IF IV_TRKORR IS INITIAL.
    EV_MESSAGE = 'TRKORR_REQUIRED'.
    RETURN.
  ENDIF.

  AUTHORITY-CHECK OBJECT 'S_TRANSPRT'
    ID 'ACTVT' FIELD '43'
    ID 'TTYPE' FIELD 'K'.
  IF SY-SUBRC <> 0.
    EV_MESSAGE = 'AUTHORIZATION_FAILED'.
    RETURN.
  ENDIF.

* --- Parent header ---
  SELECT SINGLE TRFUNCTION TRSTATUS AS4USER STRKORR
    INTO (LV_TRFUNCTION, LV_TRSTATUS,
          LV_AS4USER, LV_STRKORR)
    FROM E070
    WHERE TRKORR = IV_TRKORR.
  IF SY-SUBRC <> 0.
    EV_MESSAGE = 'REQUEST_NOT_FOUND'.
    RETURN.
  ENDIF.
  IF LV_AS4USER <> SY-UNAME.
    EV_MESSAGE = 'NOT_OWNER'.
    RETURN.
  ENDIF.
  IF LV_STRKORR IS NOT INITIAL.
    EV_MESSAGE = 'NOT_A_PARENT_REQUEST'.
    RETURN.
  ENDIF.
  IF LV_TRFUNCTION <> 'K' AND LV_TRFUNCTION <> 'W'.
    EV_MESSAGE = 'INVALID_REQUEST_TYPE'.
    RETURN.
  ENDIF.
  IF LV_TRSTATUS <> 'D'.
    IF LV_TRSTATUS = 'R' OR LV_TRSTATUS = 'N'.
      EV_MESSAGE = 'ALREADY_RELEASED'.
    ELSE.
      EV_MESSAGE = 'REQUEST_NOT_MODIFIABLE'.
    ENDIF.
    RETURN.
  ENDIF.

  SELECT SINGLE AS4TEXT INTO LV_AS4TEXT
    FROM E07T
    WHERE TRKORR = IV_TRKORR AND LANGU = 'E'.
  IF SY-SUBRC <> 0.
    SELECT SINGLE AS4TEXT INTO LV_AS4TEXT
      FROM E07T WHERE TRKORR = IV_TRKORR.
  ENDIF.

  SELECT * INTO TABLE LT_CHILDREN
    FROM E070
    WHERE STRKORR = IV_TRKORR
    ORDER BY TRKORR.

  LV_SEQ = 0.
  LV_HAS_ERROR = SPACE.

  LOOP AT LT_CHILDREN INTO LS_CHILD.
    LV_SEQ = LV_SEQ + 1.
    LV_SEQ_C = LV_SEQ.
    CONDENSE LV_SEQ_C.

    CLEAR LV_CHILD_TEXT.
    SELECT SINGLE AS4TEXT INTO LV_CHILD_TEXT
      FROM E07T
      WHERE TRKORR = LS_CHILD-TRKORR
        AND LANGU = 'E'.
    IF SY-SUBRC <> 0.
      SELECT SINGLE AS4TEXT INTO LV_CHILD_TEXT
        FROM E07T
        WHERE TRKORR = LS_CHILD-TRKORR.
    ENDIF.

*   --- Already released: nothing to do ---
    IF LS_CHILD-TRSTATUS = 'R'
      OR LS_CHILD-TRSTATUS = 'N'.
      CLEAR LV_BUF.
      CONCATENATE LS_CHILD-TRKORR
        LS_CHILD-TRFUNCTION LV_CHILD_TEXT
        'SKIPPED' 'Already released' LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.
      CONTINUE.
    ENDIF.

*   --- Not modifiable: hard error ---
    IF LS_CHILD-TRSTATUS <> 'D'.
      CLEAR LV_BUF.
      CONCATENATE LS_CHILD-TRKORR
        LS_CHILD-TRFUNCTION LV_CHILD_TEXT
        'ERROR' 'Task not modifiable' LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.
      LV_HAS_ERROR = 'X'.
      CONTINUE.
    ENDIF.

*   --- TEST_RUN: report readiness only ---
    IF IV_MODE = 'TEST_RUN'.
      REFRESH LT_OBJECTS.
      SELECT * INTO TABLE LT_OBJECTS
        FROM E071
        WHERE TRKORR = LS_CHILD-TRKORR.
      DESCRIBE TABLE LT_OBJECTS LINES LV_OBJ_CNT.
      CLEAR LV_BUF.
      IF LV_OBJ_CNT = 0.
        CONCATENATE LS_CHILD-TRKORR
          LS_CHILD-TRFUNCTION LV_CHILD_TEXT
          'WARNING' 'Task has no objects' LV_SEQ_C
          INTO LV_BUF SEPARATED BY '|'.
      ELSE.
        CLEAR LS_REQUEST.
        REFRESH LT_MESSAGES.
        CALL FUNCTION 'TR_READ_REQUEST'
          EXPORTING
            IV_TRKORR         = LS_CHILD-TRKORR
            IV_READ_E070      = 'X'
            IV_READ_E07T      = 'X'
            IV_READ_OBJS_KEYS = 'X'
          CHANGING
            CS_REQUEST        = LS_REQUEST
          EXCEPTIONS
            ERROR_OCCURED     = 1
            NO_AUTHORIZATION  = 2
            OTHERS            = 3.
        LV_CHECK_RC = SY-SUBRC.
        LV_TASK_STATUS = 'PASS'.
        LV_TASK_MESSAGE = 'Ready for release'.

        IF LV_CHECK_RC <> 0.
          LV_TASK_STATUS = 'ERROR'.
          LV_TASK_MESSAGE = 'Unable to read request objects'.
        ELSE.
          CALL FUNCTION 'TR_CHECK_REQUEST'
            EXPORTING
              IS_REQUEST          = LS_REQUEST
              IV_CHECK_LOCKABILITY = 'X'
              IV_COLLECT_MODE     = 'X'
            IMPORTING
              ET_MESSAGES         = LT_MESSAGES
            EXCEPTIONS
              ATTRIBUTE_ERROR     = 1
              HEADER_ERROR        = 2
              OBJ_OR_KEY_ERROR    = 3
              OTHERS              = 4.
          LV_CHECK_RC = SY-SUBRC.

          LOOP AT LT_MESSAGES INTO LS_MESSAGE.
            CLEAR LV_MSG_TEXT.
            MESSAGE ID LS_MESSAGE-MSGID TYPE 'S'
              NUMBER LS_MESSAGE-MSGNO
              WITH LS_MESSAGE-MSGV1 LS_MESSAGE-MSGV2
                   LS_MESSAGE-MSGV3 LS_MESSAGE-MSGV4
              INTO LV_MSG_TEXT.
            IF LS_MESSAGE-MSGTY = 'E'
              OR LS_MESSAGE-MSGTY = 'A'
              OR LS_MESSAGE-MSGTY = 'X'.
              LV_TASK_STATUS = 'ERROR'.
              LV_TASK_MESSAGE = LV_MSG_TEXT.
            ELSEIF LS_MESSAGE-MSGTY = 'W'
              AND LV_TASK_STATUS <> 'ERROR'.
              LV_TASK_STATUS = 'WARNING'.
              LV_TASK_MESSAGE = LV_MSG_TEXT.
            ENDIF.
          ENDLOOP.

          IF LV_CHECK_RC <> 0 AND LV_TASK_STATUS <> 'ERROR'.
            LV_TASK_STATUS = 'ERROR'.
            LV_TASK_MESSAGE = 'Request consistency check failed'.
          ENDIF.

*         Use SAP's own release-time inactive check. It covers every
*         R3TR/LIMU object and delegates type-specific checks internally.
          REFRESH LT_INACTIVE_LOG.
          CLEAR LS_RELEASE_E070.
          MOVE-CORRESPONDING LS_CHILD TO LS_RELEASE_E070.
          CALL FUNCTION 'TRINT_CHECK_INACTIVE_OBJECTS'
            EXPORTING
              IS_E070 = LS_RELEASE_E070
              IT_E071 = LT_OBJECTS
            TABLES
              ET_LOG  = LT_INACTIVE_LOG.

          LOOP AT LT_INACTIVE_LOG INTO LS_INACTIVE_LOG
            WHERE SEVERITY = 'W'
               OR SEVERITY = 'E'
               OR SEVERITY = 'A'.
            CLEAR LV_INACTIVE_TEXT.
            MESSAGE ID LS_INACTIVE_LOG-AG TYPE 'S'
              NUMBER LS_INACTIVE_LOG-MSGNR
              WITH LS_INACTIVE_LOG-VAR1 LS_INACTIVE_LOG-VAR2
                   LS_INACTIVE_LOG-VAR3 LS_INACTIVE_LOG-VAR4
              INTO LV_INACTIVE_TEXT.
            LV_TASK_STATUS = 'ERROR'.
            IF LV_INACTIVE_TEXT IS INITIAL.
              CONCATENATE 'Inactive object:'
                LS_INACTIVE_LOG-VAR1 LS_INACTIVE_LOG-VAR2
                INTO LV_TASK_MESSAGE SEPARATED BY SPACE.
            ELSE.
              LV_TASK_MESSAGE = LV_INACTIVE_TEXT.
            ENDIF.
            EXIT.
          ENDLOOP.
        ENDIF.

        CONCATENATE LS_CHILD-TRKORR
          LS_CHILD-TRFUNCTION LV_CHILD_TEXT
          LV_TASK_STATUS LV_TASK_MESSAGE LV_SEQ_C
          INTO LV_BUF SEPARATED BY '|'.
      ENDIF.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.

      IF LV_OBJ_CNT > 0.
        LV_OBJ_SEQ = 0.
        LOOP AT LT_OBJECTS INTO LS_OBJECT.
          LV_OBJ_SEQ = LV_OBJ_SEQ + 1.
          LV_OBJ_SEQ_C = LV_OBJ_SEQ.
          CONDENSE LV_OBJ_SEQ_C.
          LV_OBJ_STATUS = 'PASS'.
          LV_OBJ_MESSAGE = 'CTS and inactive-state validation passed'.

          LOOP AT LT_MESSAGES INTO LS_MESSAGE
            WHERE K_PGMID = LS_OBJECT-PGMID
              AND K_OBJECT = LS_OBJECT-OBJECT
              AND K_OBJNAME = LS_OBJECT-OBJ_NAME.
            CLEAR LV_MSG_TEXT.
            MESSAGE ID LS_MESSAGE-MSGID TYPE 'S'
              NUMBER LS_MESSAGE-MSGNO
              WITH LS_MESSAGE-MSGV1 LS_MESSAGE-MSGV2
                   LS_MESSAGE-MSGV3 LS_MESSAGE-MSGV4
              INTO LV_MSG_TEXT.
            IF LS_MESSAGE-MSGTY = 'E'
              OR LS_MESSAGE-MSGTY = 'A'
              OR LS_MESSAGE-MSGTY = 'X'.
              LV_OBJ_STATUS = 'ERROR'.
              LV_OBJ_MESSAGE = LV_MSG_TEXT.
              EXIT.
            ELSEIF LS_MESSAGE-MSGTY = 'W'
              AND LV_OBJ_STATUS <> 'ERROR'.
              LV_OBJ_STATUS = 'WARNING'.
              LV_OBJ_MESSAGE = LV_MSG_TEXT.
            ENDIF.
          ENDLOOP.

          LOOP AT LT_INACTIVE_LOG INTO LS_INACTIVE_LOG
            WHERE VAR2 = LS_OBJECT-OBJ_NAME
              AND ( SEVERITY = 'W'
                 OR SEVERITY = 'E'
                 OR SEVERITY = 'A' ).
            LV_OBJ_STATUS = 'ERROR'.
            CONCATENATE 'Inactive object:'
              LS_INACTIVE_LOG-VAR1 LS_INACTIVE_LOG-VAR2
              INTO LV_OBJ_MESSAGE SEPARATED BY SPACE.
            EXIT.
          ENDLOOP.

          CLEAR LV_BUF.
          CONCATENATE 'OBJECT' LS_CHILD-TRKORR
            LS_OBJECT-PGMID LS_OBJECT-OBJECT
            LS_OBJECT-OBJ_NAME LV_OBJ_STATUS
            LV_OBJ_MESSAGE LV_OBJ_SEQ_C
            INTO LV_BUF SEPARATED BY '|'.
          LV_LINE-LINE = LV_BUF.
          APPEND LV_LINE TO ET_RESULTS.
        ENDLOOP.

        IF LV_TASK_STATUS = 'ERROR'.
          LV_HAS_ERROR = 'X'.
        ENDIF.
      ENDIF.
      CONTINUE.
    ENDIF.

*   --- RELEASE: skip empty tasks ---
    REFRESH LT_OBJECTS.
    SELECT * INTO TABLE LT_OBJECTS
      FROM E071
      WHERE TRKORR = LS_CHILD-TRKORR.
    DESCRIBE TABLE LT_OBJECTS LINES LV_OBJ_CNT.
    IF LV_OBJ_CNT = 0.
      CLEAR LV_BUF.
      CONCATENATE LS_CHILD-TRKORR
        LS_CHILD-TRFUNCTION LV_CHILD_TEXT
        'SKIPPED' 'Empty task skipped' LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.
      CONTINUE.
    ENDIF.

*   --- RELEASE: release this task ---
    CALL FUNCTION 'TR_RELEASE_REQUEST'
      EXPORTING
        IV_TRKORR             = LS_CHILD-TRKORR
        IV_DIALOG             = ' '
        IV_AS_BACKGROUND_JOB  = 'X'
        IV_SUCCESS_MESSAGE    = ' '
        IV_DISPLAY_EXPORT_LOG = ' '
      EXCEPTIONS
        ACTION_ABORTED_BY_USER     = 1
        CTS_INITIALIZATION_FAILURE = 2
        DB_ACCESS_ERROR            = 3
        DOCU_MISSING               = 4
        ENQUEUE_FAILED             = 5
        ERROR_IN_EXPORT_METHODS    = 6
        EXPORT_FAILED              = 7
        INVALID_REQUEST            = 8
        NO_AUTHORIZATION           = 9
        OBJECT_CHECK_ERROR         = 10
        REPEAT_TOO_EARLY           = 11
        REQUEST_ALREADY_RELEASED   = 12
        OTHERS                     = 13.
    LV_SUBRC = SY-SUBRC.

    CLEAR: LV_BUF, LV_TASK_STATUS, LV_TASK_MESSAGE.
    IF LV_SUBRC = 0.
      LV_TASK_STATUS = 'RELEASED'.
      LV_TASK_MESSAGE = 'Released'.
    ELSEIF LV_SUBRC = 12.
      LV_TASK_STATUS = 'SKIPPED'.
      LV_TASK_MESSAGE = 'Already released'.
    ELSE.
      LV_RC_C = LV_SUBRC.
      CONDENSE LV_RC_C.
      LV_TASK_STATUS = 'ERROR'.
      CONCATENATE 'Release failed RC' LV_RC_C
        INTO LV_TASK_MESSAGE SEPARATED BY SPACE.
      LV_HAS_ERROR = 'X'.
    ENDIF.
    CONCATENATE LS_CHILD-TRKORR
      LS_CHILD-TRFUNCTION LV_CHILD_TEXT
      LV_TASK_STATUS LV_TASK_MESSAGE LV_SEQ_C
      INTO LV_BUF SEPARATED BY '|'.
    LV_LINE-LINE = LV_BUF.
    APPEND LV_LINE TO ET_RESULTS.

    LV_OBJ_SEQ = 0.
    LOOP AT LT_OBJECTS INTO LS_OBJECT.
      LV_OBJ_SEQ = LV_OBJ_SEQ + 1.
      LV_OBJ_SEQ_C = LV_OBJ_SEQ.
      CONDENSE LV_OBJ_SEQ_C.
      CLEAR LV_BUF.
      CONCATENATE 'OBJECT' LS_CHILD-TRKORR
        LS_OBJECT-PGMID LS_OBJECT-OBJECT LS_OBJECT-OBJ_NAME
        LV_TASK_STATUS LV_TASK_MESSAGE LV_OBJ_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.
    ENDLOOP.
  ENDLOOP.

* --- Parent entry ---
  LV_SEQ = LV_SEQ + 1.
  LV_SEQ_C = LV_SEQ.
  CONDENSE LV_SEQ_C.

  IF IV_MODE = 'TEST_RUN'.
    CLEAR LV_BUF.
    IF LV_HAS_ERROR = 'X'.
      CONCATENATE IV_TRKORR LV_TRFUNCTION LV_AS4TEXT
        'ERROR' 'Blocked by task errors' LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.
      EV_MESSAGE = 'TEST_RUN_HAS_ERRORS'.
    ELSE.
      CONCATENATE IV_TRKORR LV_TRFUNCTION LV_AS4TEXT
        'PASS' 'Ready for release' LV_SEQ_C
        INTO LV_BUF SEPARATED BY '|'.
      LV_LINE-LINE = LV_BUF.
      APPEND LV_LINE TO ET_RESULTS.
      EV_SUCCESS = 'X'.
      EV_MESSAGE = 'TEST_RUN_OK'.
    ENDIF.
    RETURN.
  ENDIF.

* --- Do not release parent if a task failed ---
  IF LV_HAS_ERROR = 'X'.
    CLEAR LV_BUF.
    CONCATENATE IV_TRKORR LV_TRFUNCTION LV_AS4TEXT
      'ERROR' 'Blocked by task errors' LV_SEQ_C
      INTO LV_BUF SEPARATED BY '|'.
    LV_LINE-LINE = LV_BUF.
    APPEND LV_LINE TO ET_RESULTS.
    EV_MESSAGE = 'PARTIAL_RELEASE_TASK_FAILED'.
    RETURN.
  ENDIF.

* --- Release parent ---
  CALL FUNCTION 'TR_RELEASE_REQUEST'
    EXPORTING
      IV_TRKORR             = IV_TRKORR
      IV_DIALOG             = ' '
      IV_AS_BACKGROUND_JOB  = 'X'
      IV_SUCCESS_MESSAGE    = ' '
      IV_DISPLAY_EXPORT_LOG = ' '
    EXCEPTIONS
      ACTION_ABORTED_BY_USER     = 1
      CTS_INITIALIZATION_FAILURE = 2
      DB_ACCESS_ERROR            = 3
      DOCU_MISSING               = 4
      ENQUEUE_FAILED             = 5
      ERROR_IN_EXPORT_METHODS    = 6
      EXPORT_FAILED              = 7
      INVALID_REQUEST            = 8
      NO_AUTHORIZATION           = 9
      OBJECT_CHECK_ERROR         = 10
      REPEAT_TOO_EARLY           = 11
      REQUEST_ALREADY_RELEASED   = 12
      OTHERS                     = 13.
  LV_SUBRC = SY-SUBRC.

  CLEAR LV_BUF.
  IF LV_SUBRC = 0.
    CONCATENATE IV_TRKORR LV_TRFUNCTION LV_AS4TEXT
      'RELEASED' 'Released' LV_SEQ_C
      INTO LV_BUF SEPARATED BY '|'.
    LV_LINE-LINE = LV_BUF.
    APPEND LV_LINE TO ET_RESULTS.
    EV_SUCCESS = 'X'.
    EV_MESSAGE = 'RELEASE_COMPLETE'.
  ELSEIF LV_SUBRC = 12.
    CONCATENATE IV_TRKORR LV_TRFUNCTION LV_AS4TEXT
      'SKIPPED' 'Already released' LV_SEQ_C
      INTO LV_BUF SEPARATED BY '|'.
    LV_LINE-LINE = LV_BUF.
    APPEND LV_LINE TO ET_RESULTS.
    EV_SUCCESS = 'X'.
    EV_MESSAGE = 'RELEASE_COMPLETE'.
  ELSE.
    LV_RC_C = LV_SUBRC.
    CONDENSE LV_RC_C.
    CONCATENATE IV_TRKORR LV_TRFUNCTION LV_AS4TEXT
      'ERROR' LV_RC_C LV_SEQ_C
      INTO LV_BUF SEPARATED BY '|'.
    LV_LINE-LINE = LV_BUF.
    APPEND LV_LINE TO ET_RESULTS.
    EV_MESSAGE = 'PARENT_RELEASE_FAILED'.
  ENDIF.

ENDFUNCTION.
